export const messages = [
  {
    user: "Alice Dupont",
    date: "2024-10-31T18:34:56",
    profilPicture: "https://randomuser.me/api/portraits/women/1.jpg",
    unseen: 3,
    content: "Salut ! Comment ça va ?",
  },
  {
    user: "Bob Martin",
    date: "2024-10-28T13:10:21",
    profilPicture: "https://randomuser.me/api/portraits/men/2.jpg",
    unseen: 1,
    content: "J'ai trouvé un truc intéressant pour notre projet.",
  },
  {
    user: "Charlie Lambert",
    date: "2024-10-28T15:22:39",
    profilPicture: "https://randomuser.me/api/portraits/men/3.jpg",
    unseen: 0,
    content: "Tu es libre pour une réunion cette semaine ?",
  },
  {
    user: "David Moreau",
    date: "2024-10-28T16:44:10",
    profilPicture: "https://randomuser.me/api/portraits/men/4.jpg",
    unseen: 0,
    content: "Est-ce que tu as vu le dernier épisode ?",
  },
  {
    user: "Emma Lefevre",
    date: "2024-10-28T17:50:55",
    profilPicture: "https://randomuser.me/api/portraits/women/5.jpg",
    unseen: 2,
    content: "J'ai un problème avec mon code. Tu pourrais m'aider ?",
  },
  {
    user: "Fiona Bertrand",
    date: "2024-10-28T18:05:37",
    profilPicture: "https://randomuser.me/api/portraits/women/6.jpg",
    unseen: 0,
    content: "On pourrait faire un brainstorming ensemble.",
  },
  {
    user: "George Petit",
    date: "2024-10-28T19:30:20",
    profilPicture: "https://randomuser.me/api/portraits/men/7.jpg",
    unseen: 0,
    content: "Je te partage les documents tout de suite.",
  },
  {
    user: "Hannah Girard",
    date: "2024-10-28T20:18:42",
    profilPicture: "https://randomuser.me/api/portraits/women/8.jpg",
    unseen: 0,
    content: "On se retrouve demain matin ?",
  },
  {
    user: "Ivan Dupuis",
    date: "2024-10-28T21:45:15",
    profilPicture: "https://randomuser.me/api/portraits/men/9.jpg",
    unseen: 0,
    content: "Je pense qu'on devrait changer de stratégie.",
  },
  {
    user: "Julia Roux",
    date: "2024-10-28T22:12:54",
    profilPicture: "https://randomuser.me/api/portraits/women/10.jpg",
    unseen: 3,
    content: "Tu as des recommandations pour notre projet ?",
  },
  {
    user: "Kevin Bernard",
    date: "2024-10-29T08:27:36",
    profilPicture: "https://randomuser.me/api/portraits/men/11.jpg",
    unseen: 1,
    content: "On devrait faire un point d'ici la fin de semaine.",
  },
  {
    user: "Luna Colin",
    date: "2024-10-29T09:03:29",
    profilPicture: "https://randomuser.me/api/portraits/women/12.jpg",
    unseen: 0,
    content: "J'ai fini de réviser la présentation.",
  },
  {
    user: "Michael Simon",
    date: "2024-10-29T10:19:44",
    profilPicture: "https://randomuser.me/api/portraits/men/13.jpg",
    unseen: 0,
    content: "J'aimerais avoir ton retour sur le design.",
  },
  {
    user: "Nina Lefevre",
    date: "2024-10-29T11:30:51",
    profilPicture: "https://randomuser.me/api/portraits/women/14.jpg",
    unseen: 1,
    content: "Je te fais un résumé du meeting.",
  },
  {
    user: "Oscar Fabre",
    date: "2024-10-29T12:48:12",
    profilPicture: "https://randomuser.me/api/portraits/men/15.jpg",
    unseen: 2,
    content: "Voici le lien pour accéder au document.",
  },
  {
    user: "Paula Guerin",
    date: "2024-10-29T13:25:05",
    profilPicture: "https://randomuser.me/api/portraits/women/16.jpg",
    unseen: 0,
    content: "Tu pourrais m'envoyer les fichiers du projet ?",
  },
  {
    user: "Quentin Perrot",
    date: "2024-10-29T14:41:38",
    profilPicture: "https://randomuser.me/api/portraits/men/17.jpg",
    unseen: 1,
    content: "J'ai quelques idées pour améliorer le code.",
  },
  {
    user: "Rita Roussel",
    date: "2024-10-29T15:55:45",
    profilPicture: "https://randomuser.me/api/portraits/women/18.jpg",
    unseen: 4,
    content: "On pourrait se rencontrer pour discuter.",
  },
  {
    user: "Steve Leroux",
    date: "2024-10-29T16:22:17",
    profilPicture: "https://randomuser.me/api/portraits/men/19.jpg",
    unseen: 3,
    content: "Est-ce que tu as reçu le mail ?",
  },
  {
    user: "Tina Clement",
    date: "2024-10-29T17:38:09",
    profilPicture: "https://randomuser.me/api/portraits/women/20.jpg",
    unseen: 2,
    content: "Peux-tu vérifier le fichier que je t'ai envoyé ?",
  },
];

export const discussion = [
  { sender: "Alice", receive: "Bob", content: "Salut Bob ! Comment ça va ?", date: new Date("2023-10-10T10:05:00") },
  { sender: "Bob", receive: "Alice", content: "Salut Alice ! Ça va bien, et toi ?", date: new Date("2023-10-10T10:06:00") },
  { sender: "Alice", receive: "Bob", content: "Je vais bien aussi, merci ! Tu as avancé sur le projet ?", date: new Date("2023-10-10T10:07:30") },
  { sender: "Bob", receive: "Alice", content: "Oui, j’ai terminé la première partie. Je te montre ça bientôt.", date: new Date("2023-10-10T10:08:15") },
  { sender: "Alice", receive: "Bob", content: "Super ! J’ai hâte de voir.", date: new Date("2023-10-10T10:09:00") },
  { sender: "Bob", receive: "Alice", content: "Ça devrait être bon pour demain. Je te l’envoie ce soir.", date: new Date("2023-10-10T10:10:30") },
  { sender: "Alice", receive: "Bob", content: "Parfait, je pourrais réviser avant notre réunion.", date: new Date("2023-10-10T10:12:00") },
  { sender: "Bob", receive: "Alice", content: "Exactement. As-tu des retours sur la première version ?", date: new Date("2023-10-10T10:13:20") },
  { sender: "Alice", receive: "Bob", content: "Oui, je pense qu’on pourrait améliorer l’interface.", date: new Date("2023-10-10T10:15:00") },
  { sender: "Bob", receive: "Alice", content: "Bonne idée ! Je vais voir ce que je peux faire.", date: new Date("2023-10-10T10:16:00") },
  { sender: "Alice", receive: "Bob", content: "Cool ! Je te laisse gérer cette partie alors.", date: new Date("2023-10-10T10:17:00") },
  { sender: "Bob", receive: "Alice", content: "Merci, je te tiens au courant dès que c’est prêt.", date: new Date("2023-10-10T10:18:30") },
  { sender: "Alice", receive: "Bob", content: "D’accord ! Bonne chance.", date: new Date("2023-10-10T10:19:00") },
  { sender: "Bob", receive: "Alice", content: "Merci ! À plus tard.", date: new Date("2023-10-10T10:20:30") },
  { sender: "Alice", receive: "Bob", content: "Dis-moi, tu as des nouvelles pour notre client ?", date: new Date("2023-10-10T15:30:00") },
  { sender: "Bob", receive: "Alice", content: "Pas encore, ils devraient répondre aujourd'hui.", date: new Date("2023-10-10T15:32:00") },
  { sender: "Alice", receive: "Bob", content: "J'espère qu'ils vont aimer le design qu’on a proposé.", date: new Date("2023-10-10T15:33:30") },
  { sender: "Bob", receive: "Alice", content: "Moi aussi. On verra bien !", date: new Date("2023-10-10T15:34:15") },
  { sender: "Alice", receive: "Bob", content: "Je croise les doigts.", date: new Date("2023-10-10T15:35:20") },
  { sender: "Bob", receive: "Alice", content: "Exactement. Ça va bien se passer.", date: new Date("2023-10-10T15:36:00") },
  { sender: "Alice", receive: "Bob", content: "Est-ce que tu pourrais aussi checker les stats d’audience ?", date: new Date("2023-10-10T15:37:30") },
  { sender: "Bob", receive: "Alice", content: "Bien sûr ! Je fais ça maintenant.", date: new Date("2023-10-10T15:38:20") },
  { sender: "Alice", receive: "Bob", content: "Merci beaucoup !", date: new Date("2023-10-10T15:39:10") },
  { sender: "Bob", receive: "Alice", content: "Pas de souci !", date: new Date("2023-10-10T15:40:00") },
  { sender: "Alice", receive: "Bob", content: "Tu as reçu les fichiers de Paul ?", date: new Date("2023-10-11T09:05:00") },
  { sender: "Bob", receive: "Alice", content: "Oui, je les ai reçus hier soir.", date: new Date("2023-10-11T09:06:10") },
  { sender: "Alice", receive: "Bob", content: "Parfait, je vais les examiner aujourd’hui.", date: new Date("2023-10-11T09:07:30") },
  { sender: "Bob", receive: "Alice", content: "Ça marche !", date: new Date("2023-10-11T09:08:40") },
  { sender: "Alice", receive: "Bob", content: "Au fait, es-tu disponible pour un appel cet après-midi ?", date: new Date("2023-10-11T09:10:00") },
  { sender: "Bob", receive: "Alice", content: "Oui, bien sûr. Vers quelle heure ?", date: new Date("2023-10-11T09:11:20") },
  { sender: "Alice", receive: "Bob", content: "Vers 15h ça te va ?", date: new Date("2023-10-11T09:12:30") },
  { sender: "Bob", receive: "Alice", content: "C’est parfait pour moi.", date: new Date("2023-10-11T09:13:15") },
  { sender: "Alice", receive: "Bob", content: "Super ! À tout à l'heure.", date: new Date("2023-10-11T09:14:00") },
  { sender: "Bob", receive: "Alice", content: "À plus tard !", date: new Date("2023-10-11T09:15:00") },
  { sender: "Alice", receive: "Bob", content: "Est-ce que tu as trouvé des erreurs dans le code ?", date: new Date("2023-10-11T13:30:00") },
  { sender: "Bob", receive: "Alice", content: "Quelques-unes, mais rien de grave.", date: new Date("2023-10-11T13:32:10") },
  { sender: "Alice", receive: "Bob", content: "Super, ça me rassure !", date: new Date("2023-10-11T13:33:30") },
  { sender: "Bob", receive: "Alice", content: "Oui, rien de majeur. On est sur la bonne voie.", date: new Date("2023-10-11T13:35:00") },
  { sender: "Alice", receive: "Bob", content: "Merci pour ton aide !", date: new Date("2023-10-11T13:36:20") },
  { sender: "Bob", receive: "Alice", content: "Avec plaisir, toujours là pour ça.", date: new Date("2023-10-11T13:37:30") },
  { sender: "Alice", receive: "Bob", content: "As-tu besoin d’aide pour la partie backend ?", date: new Date("2023-10-12T10:00:00") },
  { sender: "Bob", receive: "Alice", content: "Oui, si tu as du temps ce soir.", date: new Date("2023-10-12T10:01:15") },
  { sender: "Alice", receive: "Bob", content: "Bien sûr, je suis dispo après 18h.", date: new Date("2023-10-12T10:02:30") },
  { sender: "Bob", receive: "Alice", content: "Génial ! Merci beaucoup.", date: new Date("2023-10-12T10:04:00") },
  { sender: "Alice", receive: "Bob", content: "Pas de souci, on va y arriver ensemble.", date: new Date("2023-10-12T10:05:10") },
  { sender: "Bob", receive: "Alice", content: "Absolument !", date: new Date("2023-10-12T10:06:30") },
]